PREFIX : <http://ex.org/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX uom: <http://www.opengis.net/def/uom/OGC/1.0/>
SELECT ?v WHERE {
  ?x a :Geog ; geo:asWKT ?xWkt .
  ?x rdfs:label ?xname .
  ?y a :NewGeom ; geo:asWKT ?yWkt .
  ?y rdfs:label ?yname .
  BIND(geof:buffer(?xWkt, 20, uom:metre) AS ?zWkt) .
  FILTER(?xname = ?yname) .
  BIND(geof:intersection(?zWkt, ?yWkt) AS ?v)
} LIMIT 1
