PREFIX : <https://example.test/datatypes#>
SELECT ?boolean ?character ?numeric ?real ?double ?date ?time ?timetz ?timestamp ?timestamptz {
  :row-1 :boolean ?boolean .
  :row-1 :character ?character .
  :row-1 :numeric ?numeric .
  :row-1 :real ?real .
  :row-1 :double ?double .
  :row-1 :date ?date .
  :row-1 :time ?time .
  :row-1 :timetz ?timetz .
  :row-1 :timestamp ?timestamp .
  :row-1 :timestamptz ?timestamptz .
}
