PREFIX : <http://www.semanticweb.org/user/ontologies/2016/8/untitled-ontology-84#>
SELECT ?p (AVG(?n) AS ?v) WHERE {
  ?p :teaches ?c .
  { ?c :duration ?n }
  UNION
  { ?c :nbStudents ?n }
}
GROUP BY ?p
ORDER BY ?v
