PREFIX : <http://www.semanticweb.org/user/ontologies/2016/8/untitled-ontology-84#>
SELECT ?v ?f WHERE {
  ?p a :Professor ; :firstName ?f ; :teaches ?c .
  OPTIONAL { ?p :nickname ?v }
}
ORDER BY DESC(?v)
