PREFIX : <http://www.semanticweb.org/user/ontologies/2016/8/untitled-ontology-84#>
SELECT ?p (SUM(?nb) AS ?v) WHERE {
  ?p a :Professor .
  OPTIONAL {
    ?p :teaches ?c .
    ?c :nbStudents ?nb .
  }
}
GROUP BY ?p
ORDER BY ?v
