PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX ns: <http://example.org/ns#>

SELECT ?value WHERE {
  ?x ns:price ?price .
  ?x ns:discount ?discount .
  ?x dc:title ?title .
  ?x ns:pubYear ?year .
  FILTER(STRSTARTS(?title, "The"))
  BIND(ENCODE_FOR_URI(?title) AS ?value)
}
ORDER BY ?title
