BASE <http://example.org/>
SELECT ?w {
  { VALUES ?v { "john" "ernest" "http://example.org/alice" } }
  UNION
  { BIND(STR(RAND()) AS ?v) }
  BIND(IRI(?v) AS ?w)
  VALUES ?y { <http://example.org/john> <http://otherdomain.org/ernest> }
  FILTER (?w = ?y)
}
