PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX ns: <http://example.org/ns#>

SELECT ?title ?hash WHERE {
  ?x ns:price ?price .
  ?x ns:discount ?discount .
  ?x dc:title ?title .
  FILTER(STRSTARTS(?title, "The S"))
  BIND(SHA256(STR(?title)) AS ?hash)
}
