PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX ns: <http://example.org/ns#>

SELECT ?value WHERE {
  ?x ns:price ?price .
  ?x ns:discount ?discount .
  ?x dc:title ?title .
  BIND(SUBSTR(?title, 1, STRLEN(?title)) AS ?value)
  FILTER(STRSTARTS(?title, "The"))
}
ORDER BY ?title
